### ISSUE TITLE
Bugs: when computing higher order difference. 

### ISSUE THREAD

**Issue by wangmiaowei** [martenlienen/torchode#36] opened 2024-03-05 20:11 UTC
```
#import matplotlib.pyplot as pp
import torch
import torchode as to
import torch.autograd as ag
import torch.nn as nn
def df(x,wrt):
    
    M = x.shape[0]
    return ag.grad(x.flatten(), wrt,
                       grad_outputs=torch.ones(M, dtype=torch.float32).to(wrt.device),create_graph=True)[0]
class Model(nn.Module):
    def __init__(self, n_features, n_hidden):
        super().__init__()
        self.layers = nn.Sequential(
            nn.Linear(n_features, n_hidden),
            nn.Softplus(),
            nn.Linear(n_hidden, n_hidden),
            nn.Softplus(),
            nn.Linear(n_hidden, n_features)
        )
    
    def forward(self, t, y):
        return self.layers(y)
n_features = 3
model = Model(n_features=n_features, n_hidden=32)
dev = torch.device("cuda")
term = to.ODETerm(model)
step_method = to.Dopri5(term=term)
step_size_controller = to.IntegralController(atol=1e-6, rtol=1e-3, term=term)
#step_size_controller = StepSizeControllerTracker(step_size_controller)
adjoint = to.AutoDiffAdjoint(step_method, step_size_controller).to(dev)

n_steps = 2
t_eval = torch.linspace(0, 5, n_steps).unsqueeze(0).repeat(100,1).cuda()
print('t_eval.shape: ',t_eval.shape)

optimizer = torch.optim.RMSprop(model.parameters(), lr=1e-3)
#jit_solver = torch.jit.script(adjoint)
for i in range(10):
    optimizer.zero_grad()
    y0 = torch.rand((100,3)).cuda()
    y0.requires_grad = True

    sol = adjoint.solve(to.InitialValueProblem(y0=y0, t_eval=t_eval))
    res= sol.ys
    derives = df(res[0,1,:],y0)
    loss = (derives**2).mean()
    loss.backward()
    optimizer.step()
      print('loss: ',loss)
# => {'n_f_evals': tensor([26, 26]), 'n_steps': tensor([4, 2]),
# =>  'n_accepted': tensor([4, 2]), 'n_initialized': tensor([10, 10])}

#pp.plot(sol.ts[0], sol.ys[0])
#pp.plot(sol.ts[1], sol.ys[1])
```

My errors:

```
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
```

**Comment by martenlienen** [comment] 2024-03-05 22:40
Hey, thanks for reporting this problem. Have you debugged where exactly thing are going wrong? I have not tried higher order gradients through torchode before, but I don't see any reason why it should not work with `AutoDiffAdjoint`, which just applies basic pytorch operations in a loop in the end. Where exactly is the first tensor in your code which no longer has a `grad_fn`?

**Comment by martenlienen** [comment] 2024-03-05 22:47
Does it work if you set `res = 5 * y0[None, None]` or some similar simple computation? Does `y0` need to `require_grad` for higher order gradients to work?

**Comment by wangmiaowei** [comment] 2024-03-05 22:56
Yes I have to set yo to be requires_grad=True otherwise,
```
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: One of the differentiated Tensors does not require grad
```
Currently I found I can get my results, but loss is Nan very bad haha:
```
loss:  tensor(0.3356, device='cuda:0', grad_fn=<MeanBackward0>)
loss:  tensor(nan, device='cuda:0', grad_fn=<MeanBackward0>)
loss:  tensor(nan, device='cuda:0', grad_fn=<MeanBackward0>)
loss:  tensor(nan, device='cuda:0', grad_fn=<MeanBackward0>)
loss:  tensor(nan, device='cuda:0', grad_fn=<MeanBackward0>)
loss:  tensor(nan, device='cuda:0', grad_fn=<MeanBackward0>)
loss:  tensor(nan, device='cuda:0', grad_fn=<MeanBackward0>)
loss:  tensor(nan, device='cuda:0', grad_fn=<MeanBackward0>)
loss:  tensor(nan, device='cuda:0', grad_fn=<MeanBackward0>)
loss:  tensor(nan, device='cuda:0', grad_fn=<MeanBackward0>)
```
And my code is here:
```
#import matplotlib.pyplot as pp
import torch
import torchode as to
import torch.autograd as ag
import torch.nn as nn
def df(x,wrt):
    
    M = x.shape[0]
    return ag.grad(x.flatten(), wrt,
                       grad_outputs=torch.ones(M, dtype=torch.float32).to(wrt.device),create_graph=True,retain_graph=True)[0]
class Model(nn.Module):
    def __init__(self, n_features, n_hidden):
        super().__init__()
        self.layers = nn.Sequential(
            nn.Linear(n_features, n_hidden),
            nn.Softplus(),
            nn.Linear(n_hidden, n_hidden),
            nn.Softplus(),
            nn.Linear(n_hidden, n_features)
        )
    
    def forward(self, t, y):
        return self.layers(y)
n_features = 3
model = Model(n_features=n_features, n_hidden=32)
dev = torch.device("cuda")
term = to.ODETerm(model)
step_method = to.Dopri5(term=term)
step_size_controller = to.IntegralController(atol=1e-6, rtol=1e-3, term=term)
#step_size_controller = StepSizeControllerTracker(step_size_controller)
adjoint = to.AutoDiffAdjoint(step_method, step_size_controller).to(dev)

n_steps = 2

optimizer = torch.optim.RMSprop(model.parameters(), lr=1e-7)
#jit_solver = torch.jit.script(adjoint)
for i in range(10):
    optimizer.zero_grad()
    y0 = torch.rand((10000,3)).cuda()
    t_eval = torch.linspace(0, 1, n_steps).unsqueeze(0).repeat(10000,1).cuda()
    y0.requires_grad = True

    sol = adjoint.solve(to.InitialValueProblem(y0=y0,t_start=t_eval[:,0],t_end=t_eval[:,-1] ,t_eval=None))
    res= sol.ys[:,0,:]
    dxyz_dxyz=[]
    #iden_matrix = self.identity.repeat(batch,1,1)
    for o in range(3):
        derivs = df(res[:,o],y0)
        dxyz_dxyz.append(derivs.unsqueeze(1))
    new_der = torch.cat(dxyz_dxyz,dim=1)
    loss = new_der.mean()
    loss.backward()
    optimizer.step()
    print('loss: ',loss)
# => {'n_f_evals': tensor([26, 26]), 'n_steps': tensor([4, 2]),
# =>  'n_accepted': tensor([4, 2]), 'n_initialized': tensor([10, 10])}

#pp.plot(sol.ts[0], sol.ys[0])
#pp.plot(sol.ts[1], sol.ys[1
```

**Comment by martenlienen** [comment] 2024-03-06 07:27
Then you should try `torch.autograd.set_detect_anomaly(True)` next to find the cause of NaN

**Comment by martenlienen** [comment] 2024-03-11 22:16
I will close this for now. If you find the root cause of your problem to be within torchode, please re-open it!

**Closed by martenlienen** 2024-03-11 22:16 UTC
