### ISSUE TITLE
jit error

### ISSUE THREAD

**Issue by Yue-Shen** [martenlienen/torchode#11] opened 2023-02-14 07:59 UTC
Hello, 

Thanks a lot for this great package. I tried the usage example but had the following error. Would you happen to have any idea what happens here?

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-4-4ed5c73bd717> in <module>
     14 step_size_controller = to.IntegralController(atol=1e-6, rtol=1e-3, term=term)
     15 solver = to.AutoDiffAdjoint(step_method, step_size_controller)
---> 16 jit_solver = torch.jit.script(solver)
     17 
     18 # sol = jit_solver.solve(to.InitialValueProblem(y0=y0, t_eval=t_eval))

C:\anaconda\lib\site-packages\torch\jit\_script.py in script(obj, optimize, _frames_up, _rcb, example_inputs)
   1284     if isinstance(obj, torch.nn.Module):
   1285         obj = call_prepare_scriptable_func(obj)
-> 1286         return torch.jit._recursive.create_script_module(
   1287             obj, torch.jit._recursive.infer_methods_to_compile
   1288         )

C:\anaconda\lib\site-packages\torch\jit\_recursive.py in create_script_module(nn_module, stubs_fn, share_types, is_tracing)
    474     if not is_tracing:
    475         AttributeTypeIsSupportedChecker().check(nn_module)
--> 476     return create_script_module_impl(nn_module, concrete_type, stubs_fn)
    477 
    478 def create_script_module_impl(nn_module, concrete_type, stubs_fn):

C:\anaconda\lib\site-packages\torch\jit\_recursive.py in create_script_module_impl(nn_module, concrete_type, stubs_fn)
    540     # Compile methods if necessary
    541     if concrete_type not in concrete_type_store.methods_compiled:
--> 542         create_methods_and_properties_from_stubs(concrete_type, method_stubs, property_stubs)
    543         # Create hooks after methods to ensure no name collisions between hooks and methods.
    544         # If done before, hooks can overshadow methods that aren't exported.

C:\anaconda\lib\site-packages\torch\jit\_recursive.py in create_methods_and_properties_from_stubs(concrete_type, method_stubs, property_stubs)
    391     property_rcbs = [p.resolution_callback for p in property_stubs]
    392 
--> 393     concrete_type._create_methods_and_properties(property_defs, property_rcbs, method_defs, method_rcbs, method_defaults)
    394 
    395 def create_hooks_from_stubs(concrete_type, hook_stubs, pre_hook_stubs):

RuntimeError: type INTERNAL ASSERT FAILED at "C:\\actions-runner\\_work\\pytorch\\pytorch\\builder\\windows\\pytorch\\torch/csrc/jit/ir/ir.h":1488, please report a bug to PyTorch.

**Comment by martenlienen** [comment] 2023-02-14 08:51
Do you have the exact code that you ran? And is this the complete error message? The JIT compiler is a bit finicky and often gives quite unhelpful error messages like this one. Usually, the only thing that I could do to help myself was to step into the JIT compiler with a debugger and inspect its internal state and variables until I could pinpoint what was wrong.

**Comment by Yue-Shen** [comment] 2023-02-14 18:23
Thank you for your suggestion. I will try to use a debugger to inspect.

 For now, I tried to update python to 3.10.9 and this problem still exists. The code I ran is the example code in the 'Usage' part of [README.md](https://github.com/martenlienen/torchode#readme). The new complete error message is:

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[6], line 16
     14 step_size_controller = to.IntegralController(atol=1e-6, rtol=1e-3, term=term)
     15 solver = to.AutoDiffAdjoint(step_method, step_size_controller)
---> 16 jit_solver = torch.jit.script(solver)
     18 sol = jit_solver.solve(to.InitialValueProblem(y0=y0, t_eval=t_eval))
     19 print(sol.stats)

File ~/opt/anaconda3/envs/py310/lib/python3.10/site-packages/torch/jit/_script.py:1286, in script(obj, optimize, _frames_up, _rcb, example_inputs)
   1284 if isinstance(obj, torch.nn.Module):
   1285     obj = call_prepare_scriptable_func(obj)
-> 1286     return torch.jit._recursive.create_script_module(
   1287         obj, torch.jit._recursive.infer_methods_to_compile
   1288     )
   1290 if isinstance(obj, dict):
   1291     return create_script_dict(obj)

File ~/opt/anaconda3/envs/py310/lib/python3.10/site-packages/torch/jit/_recursive.py:476, in create_script_module(nn_module, stubs_fn, share_types, is_tracing)
    474 if not is_tracing:
    475     AttributeTypeIsSupportedChecker().check(nn_module)
--> 476 return create_script_module_impl(nn_module, concrete_type, stubs_fn)

File ~/opt/anaconda3/envs/py310/lib/python3.10/site-packages/torch/jit/_recursive.py:542, in create_script_module_impl(nn_module, concrete_type, stubs_fn)
    540 # Compile methods if necessary
    541 if concrete_type not in concrete_type_store.methods_compiled:
--> 542     create_methods_and_properties_from_stubs(concrete_type, method_stubs, property_stubs)
    543     # Create hooks after methods to ensure no name collisions between hooks and methods.
    544     # If done before, hooks can overshadow methods that aren't exported.
    545     create_hooks_from_stubs(concrete_type, hook_stubs, pre_hook_stubs)

File ~/opt/anaconda3/envs/py310/lib/python3.10/site-packages/torch/jit/_recursive.py:393, in create_methods_and_properties_from_stubs(concrete_type, method_stubs, property_stubs)
    390 property_defs = [p.def_ for p in property_stubs]
    391 property_rcbs = [p.resolution_callback for p in property_stubs]
--> 393 concrete_type._create_methods_and_properties(property_defs, property_rcbs, method_defs, method_rcbs, method_defaults)

RuntimeError: type INTERNAL ASSERT FAILED at "/Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/jit/ir/ir.h":1488, please report a bug to PyTorch. 

[Usage example.zip](https://github.com/martenlienen/torchode/files/10735655/Usage.example.zip)

**Comment by martenlienen** [comment] 2023-02-14 19:27
Thank you for the report! I have reproduced it and I am stumped why the example from the readme no longer works. I traced it back to the wonky `Enum` support of the JIT compiler and have released a new version 0.1.6 on pypi that fixes it. The example now works again (at least for me).

**Comment by Yue-Shen** [comment] 2023-02-14 22:07
I am really sorry to bother you again. I upgraded the Torchode package but the problem still exists. I also tried it on different computers. Would you happen to have any idea?
[example_ode.zip](https://github.com/martenlienen/torchode/files/10737289/example_ode.zip)

**Comment by martenlienen** [comment] 2023-02-15 07:51
Hm, for me your example works. Can you report your installed package versions with `pip freeze`? For me it is
```
aiofiles==22.1.0
aiosqlite==0.18.0
anyio==3.6.2
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
arrow==1.2.3
asttokens==2.2.1
attrs==22.2.0
Babel==2.11.0
backcall==0.2.0
beautifulsoup4==4.11.2
bleach==6.0.0
certifi==2022.12.7
cffi==1.15.1
charset-normalizer==3.0.1
comm==0.1.2
contourpy==1.0.7
cycler==0.11.0
debugpy==1.6.6
decorator==5.1.1
defusedxml==0.7.1
docutils==0.19
executing==1.2.0
fastjsonschema==2.16.2
flit==3.8.0
flit_core==3.8.0
fonttools==4.38.0
fqdn==1.5.1
functorch==1.13.1
idna==3.4
iniconfig==2.0.0
ipdb==0.13.11
ipykernel==6.21.2
ipython==8.10.0
ipython-genutils==0.2.0
isoduration==20.11.0
jedi==0.18.2
Jinja2==3.1.2
json5==0.9.11
jsonpointer==2.3
jsonschema==4.17.3
jupyter-events==0.5.0
jupyter-ydoc==0.2.2
jupyter_client==8.0.2
jupyter_core==5.2.0
jupyter_server==2.2.1
jupyter_server_fileid==0.6.0
jupyter_server_terminals==0.4.4
jupyter_server_ydoc==0.6.1
jupyterlab==3.6.1
jupyterlab-pygments==0.2.2
jupyterlab_server==2.19.0
kiwisolver==1.4.4
MarkupSafe==2.1.2
matplotlib==3.7.0
matplotlib-inline==0.1.6
mistune==2.0.5
mpmath==1.2.1
nbclassic==0.5.1
nbclient==0.7.2
nbconvert==7.2.9
nbformat==5.7.3
nest-asyncio==1.5.6
notebook==6.5.2
notebook_shim==0.2.2
numpy==1.24.2
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
packaging==23.0
pandocfilters==1.5.0
parso==0.8.3
pexpect==4.8.0
pickleshare==0.7.5
Pillow==9.4.0
platformdirs==3.0.0
pluggy==1.0.0
prometheus-client==0.16.0
prompt-toolkit==3.0.36
psutil==5.9.4
ptyprocess==0.7.0
pure-eval==0.2.2
pycparser==2.21
Pygments==2.14.0
pyparsing==3.0.9
PyQt5==5.15.9
PyQt5-Qt5==5.15.2
PyQt5-sip==12.11.1
pyrsistent==0.19.3
pytest==7.2.1
python-dateutil==2.8.2
python-json-logger==2.0.6
pytz==2022.7.1
PyYAML==6.0
pyzmq==25.0.0
requests==2.28.2
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
Send2Trash==1.8.0
six==1.16.0
sniffio==1.3.0
soupsieve==2.4
stack-data==0.6.2
sympy==1.11.1
terminado==0.17.1
tinycss2==1.2.1
tomli_w==1.0.0
torch==1.13.1
-e git+ssh://git@github.com/martenlienen/torchode.git@20e750d0230915f74ada110ab7429927da8451d8#egg=torchode
torchtyping==0.1.4
tornado==6.2
traitlets==5.9.0
typeguard==2.13.3
typing_extensions==4.4.0
uri-template==1.2.0
urllib3==1.26.14
wcwidth==0.2.6
webcolors==1.12
webencodings==0.5.1
websocket-client==1.5.1
y-py==0.5.5
ypy-websocket==0.8.2
```

**Comment by Yue-Shen** [comment] 2023-02-15 08:27
Thank you so much for replying! What I have is:

Package                       Version
----------------------------- --------------------
alabaster                     0.7.12
anyio                         3.5.0
appdirs                       1.4.4
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
arrow                         1.2.3
astroid                       2.11.7
astropy                       5.1
atomicwrites                  1.4.0
attrs                         22.1.0
Automat                       20.2.0
autopep8                      1.6.0
Babel                         2.11.0
backcall                      0.2.0
bcrypt                        3.2.0
beautifulsoup4                4.11.1
binaryornot                   0.4.4
bitarray                      2.5.1
bkcharts                      0.2
black                         22.6.0
bleach                        4.1.0
bokeh                         2.4.3
boto3                         1.24.28
botocore                      1.27.59
Bottleneck                    1.3.5
brotlipy                      0.7.0
certifi                       2022.12.7
cffi                          1.15.1
chardet                       4.0.0
charset-normalizer            2.0.4
click                         8.0.4
cloudpickle                   2.0.0
clyent                        1.2.2
colorama                      0.4.6
colorcet                      3.0.1
comm                          0.1.2
comtypes                      1.1.10
constantly                    15.1.0
contourpy                     1.0.5
cookiecutter                  1.7.3
cryptography                  38.0.4
cssselect                     1.1.0
cycler                        0.11.0
Cython                        0.29.32
cytoolz                       0.12.0
daal4py                       2021.4.0
dask                          2022.5.0
datashader                    0.14.3
datashape                     0.5.4
debugpy                       1.5.1
decorator                     5.1.1
defusedxml                    0.7.1
diff-match-patch              20200713
dill                          0.3.6
distributed                   2022.5.0
docutils                      0.18.1
entrypoints                   0.4
et-xmlfile                    1.1.0
fastjsonschema                2.16.2
filelock                      3.9.0
flake8                        4.0.1
Flask                         2.2.2
flit_core                     3.6.0
fonttools                     4.25.0
fsspec                        2022.11.0
functorch                     1.13.1
gensim                        4.1.2
greenlet                      2.0.1
h5py                          3.7.0
HeapDict                      1.0.1
holoviews                     1.15.3
hvplot                        0.8.2
hyperlink                     21.0.0
idna                          3.4
imagecodecs                   2021.8.26
imageio                       2.19.3
imagesize                     1.4.1
importlib-metadata            4.11.3
incremental                   21.3.0
inflection                    0.5.1
iniconfig                     1.1.1
intake                        0.6.6
intervaltree                  3.1.0
ipykernel                     6.19.2
ipython                       7.31.1
ipython-genutils              0.2.0
ipywidgets                    7.6.5
isort                         5.9.3
itemadapter                   0.3.0
itemloaders                   1.0.4
itsdangerous                  2.0.1
jdcal                         1.4.1
jedi                          0.18.1
jellyfish                     0.9.0
Jinja2                        3.1.2
jinja2-time                   0.2.0
jmespath                      0.10.0
joblib                        1.1.1
json5                         0.9.6
jsonschema                    4.16.0
jupyter                       1.0.0
jupyter_client                7.4.8
jupyter-console               6.4.4
jupyter_core                  5.1.1
jupyter-server                1.23.4
jupyterlab                    3.5.2
jupyterlab-pygments           0.1.2
jupyterlab_server             2.16.5
jupyterlab-widgets            1.0.0
keyring                       23.4.0
kiwisolver                    1.4.4
lazy-object-proxy             1.6.0
llvmlite                      0.39.1
locket                        1.0.0
lxml                          4.9.1
lz4                           3.1.3
Markdown                      3.4.1
MarkupSafe                    2.1.1
matplotlib                    3.6.2
matplotlib-inline             0.1.6
mccabe                        0.7.0
menuinst                      1.4.19
mistune                       0.8.4
mkl-fft                       1.3.1
mkl-random                    1.2.2
mkl-service                   2.4.0
mock                          4.0.3
mpmath                        1.2.1
msgpack                       1.0.3
multipledispatch              0.6.0
munkres                       1.1.4
mypy-extensions               0.4.3
nbclassic                     0.4.8
nbclient                      0.5.13
nbconvert                     6.5.4
nbformat                      5.7.0
nest-asyncio                  1.5.6
networkx                      2.8.4
nltk                          3.7
nose                          1.3.7
notebook                      6.5.2
notebook_shim                 0.2.2
numba                         0.56.4
numexpr                       2.8.4
numpy                         1.24.2
numpydoc                      1.5.0
olefile                       0.46
openpyxl                      3.0.10
packaging                     22.0
pandas                        1.5.2
pandocfilters                 1.5.0
panel                         0.14.1
param                         1.12.3
paramiko                      2.8.1
parsel                        1.6.0
parso                         0.8.3
partd                         1.2.0
pathspec                      0.9.0
patsy                         0.5.2
pep8                          1.7.1
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        9.3.0
pip                           22.3.1
platformdirs                  2.5.2
plotly                        5.9.0
pluggy                        1.0.0
ply                           3.11
poyo                          0.5.0
prometheus-client             0.14.1
prompt-toolkit                3.0.36
Protego                       0.1.16
psutil                        5.9.0
ptyprocess                    0.7.0
py                            1.11.0
pyasn1                        0.4.8
pyasn1-modules                0.2.8
pycodestyle                   2.8.0
pycosat                       0.6.4
pycparser                     2.21
pyct                          0.4.8
pycurl                        7.45.1
PyDispatcher                  2.0.5
pydocstyle                    6.1.1
pyerfa                        2.0.0
pyflakes                      2.4.0
Pygments                      2.11.2
PyHamcrest                    2.0.2
pylint                        2.14.5
pyls-spyder                   0.4.0
PyNaCl                        1.5.0
pyodbc                        4.0.34
pyOpenSSL                     22.0.0
pyparsing                     3.0.9
PyQt5                         5.15.7
PyQt5-sip                     12.11.0
PyQtWebEngine                 5.15.4
pyrsistent                    0.18.0
PySocks                       1.7.1
pytest                        7.1.2
python-dateutil               2.8.2
python-lsp-black              1.2.1
python-lsp-jsonrpc            1.0.0
python-lsp-server             1.5.0
python-slugify                5.0.2
python-snappy                 0.6.1
pytz                          2022.7
pyviz-comms                   2.0.2
PyWavelets                    1.4.1
pywin32                       305.1
pywin32-ctypes                0.2.0
pywinpty                      2.0.2
PyYAML                        6.0
pyzmq                         23.2.0
QDarkStyle                    3.0.2
qstylizer                     0.2.2
QtAwesome                     1.2.2
qtconsole                     5.3.2
QtPy                          2.2.0
queuelib                      1.5.0
regex                         2022.7.9
requests                      2.28.1
requests-file                 1.5.1
rope                          0.22.0
Rtree                         0.9.7
ruamel.yaml.clib              0.2.6
ruamel-yaml-conda             0.17.21
s3transfer                    0.6.0
scikit-image                  0.19.3
scikit-learn                  1.2.0
scikit-learn-intelex          2021.20220113.184028
scipy                         1.9.3
Scrapy                        2.6.2
seaborn                       0.12.2
Send2Trash                    1.8.0
service-identity              18.1.0
setuptools                    65.6.3
sip                           6.6.2
six                           1.16.0
smart-open                    5.2.1
sniffio                       1.2.0
snowballstemmer               2.2.0
sortedcollections             2.1.0
sortedcontainers              2.4.0
soupsieve                     2.3.2.post1
Sphinx                        5.0.2
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
spyder                        5.3.3
spyder-kernels                2.3.3
SQLAlchemy                    1.4.39
statsmodels                   0.13.2
sympy                         1.11.1
tables                        3.7.0
tabulate                      0.8.10
TBB                           0.2
tblib                         1.7.0
tenacity                      8.0.1
terminado                     0.17.1
testpath                      0.6.0
text-unidecode                1.3
textdistance                  4.2.1
threadpoolctl                 2.2.0
three-merge                   0.1.1
tifffile                      2021.7.2
tinycss2                      1.2.1
tldextract                    3.2.0
toml                          0.10.2
tomli                         2.0.1
tomlkit                       0.11.1
toolz                         0.12.0
torch                         1.13.1
torchode                      0.1.6
torchtyping                   0.1.4
tornado                       6.2
tqdm                          4.64.1
traitlets                     5.7.1
Twisted                       22.2.0
twisted-iocpsupport           1.0.2
typeguard                     2.13.3
typing_extensions             4.4.0
ujson                         5.4.0
Unidecode                     1.2.0
urllib3                       1.26.14
w3lib                         1.21.0
watchdog                      2.1.6
wcwidth                       0.2.5
webencodings                  0.5.1
websocket-client              0.58.0
Werkzeug                      2.2.2
whatthepatch                  1.0.2
wheel                         0.37.1
widgetsnbextension            3.5.2
win-inet-pton                 1.1.0
win-unicode-console           0.5
wincertstore                  0.2
wrapt                         1.14.1
xarray                        2022.11.0
xlrd                          2.0.1
XlsxWriter                    3.0.3
xlwings                       0.27.15
yapf                          0.31.0
zict                          2.1.0
zipp                          3.11.0
zope.interface                5.4.0

**Comment by martenlienen** [comment] 2023-02-15 08:56
I don't see anything suspicious and everything looks fine. What happens if you set up a new virtual / conda environment and just install `pip install torchode matplotlib PyQt5` and then run the example again?

**Comment by Yue-Shen** [comment] 2023-02-15 09:15
Sorry, for me it just won't work. Maybe importing the conda environment I just created can help you reproduce?

[test_env.zip](https://github.com/martenlienen/torchode/files/10741278/test_env.zip)

**Comment by martenlienen** [comment] 2023-02-15 09:41
I have recreated your environment but for me it just works. Somehow it could stem from the fact that you seem to be running on another OS than linux though I don't see how that would impact the JIT compiler. So it looks like you will have to debug this yourself. You can likely find the cause if you insert some debugging `print`s or `breakpoint()`s at `~/opt/anaconda3/envs/py310/lib/python3.10/site-packages/torch/jit/recursive.py:393` and see what the offending input is exactly. If you want to use the JIT compiler, you will likely have to get accustomed to these internals anyway in my experience.

**Comment by Yue-Shen** [comment] 2023-02-15 17:01
I'll make a try. Thank you, so much!

**Comment by martenlienen** [comment] 2023-02-15 17:03
Until you find your underlying cause, I will close this issue. Feel free to reopen it, when you make some progress.

**Closed by martenlienen** 2023-02-15 17:03 UTC
